/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Admin;
import controller.Kurir;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Model;

/**
 *
 * @author USER
 */
public class V_AdminKonfirmasiPaket extends javax.swing.JFrame {
    private String id_shipment;
    private String id_barang;
    /**
     * Creates new form V_AdminKonfirmasiPaket
     */
    public V_AdminKonfirmasiPaket() {
        initComponents();
        showTable();
        showSelected();
    }
    
    public void showTable(){
        DefaultTableModel tabelBar;
        String [] judulTabel = {"Id Shipment", "Id Kurir", "Id Barang", "Status"};
        tabelBar = new DefaultTableModel(judulTabel, 0);
        jTableKonfirmasi.setModel(tabelBar);
        
        int row = jTableKonfirmasi.getRowCount();
        for (int i = 0; i < row; i++) {
            tabelBar.removeRow(0);
        }
        
        try{
            Admin a = new Admin();
            ResultSet result = a.getPaketPending();
            while(result.next()){
                String data[] = {result.getString("id_shipment"), result.getString("id_kurir"), result.getString("id_barang"), result.getString(4)};
                tabelBar.addRow(data);
            }
        }catch(Exception e){
            System.err.println("error:");
        }
    }
    
    public void showSelected(){
        jTableKonfirmasi.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
             if (e.getClickCount() == 1) {
              JTable target = (JTable)e.getSource();
              int row = target.getSelectedRow();
              int column = 0;
              Object id_ship = target.getValueAt(row, column);
              try{
                  Model m = new Model();
                  String sql = "SELECT * FROM shipment WHERE id_shipment = '"+id_ship+"'";
                  ResultSet result = m.getData(sql);
                  while(result.next()){
                      jTextIdPengiriman.setText(result.getString("id_shipment"));
                      jTextIdKurir.setText((result.getString("id_kurir")));
                      jTextIdBarang.setText(result.getString("id_barang"));
                      jTextStatus.setText(result.getString("status"));
                      id_shipment = result.getString("id_shipment");
                      id_barang = result.getString("id_barang");
                  }
              } catch(Exception ex){
                  
              }
             }
            }
           });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKonfirmasi = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButtonKonfirmasi = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jTextIdBarang = new javax.swing.JTextField();
        jTextIdKurir = new javax.swing.JTextField();
        jTextIdPengiriman = new javax.swing.JTextField();
        jTextStatus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTableKonfirmasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableKonfirmasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKonfirmasi);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 120, 840, 130);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 44)); // NOI18N
        jLabel10.setText("PACKETDOT");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 30, 280, 54);

        jButtonKonfirmasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonKonfirmasi.setText("Konfirmasi");
        jButtonKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKonfirmasiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKonfirmasi);
        jButtonKonfirmasi.setBounds(380, 500, 250, 60);

        jButtonHome.setText("BACK");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome);
        jButtonHome.setBounds(20, 20, 70, 50);
        jPanel1.add(jTextIdBarang);
        jTextIdBarang.setBounds(450, 380, 150, 30);
        jPanel1.add(jTextIdKurir);
        jTextIdKurir.setBounds(450, 350, 150, 30);
        jPanel1.add(jTextIdPengiriman);
        jTextIdPengiriman.setBounds(450, 320, 150, 30);
        jPanel1.add(jTextStatus);
        jTextStatus.setBounds(450, 410, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Status:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 410, 90, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Id Barang:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 380, 90, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Id Kurir:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 350, 90, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Id Pengiriman:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 320, 120, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("DETAIL PENGIRIMAN");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 270, 195, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bg9.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        V_AdminCekBarang a = new V_AdminCekBarang();
        a.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKonfirmasiActionPerformed
        // TODO add your handling code here:
        Admin a = new Admin(this.id_shipment);
        a.setAccPaket();
        showTable();
        JOptionPane.showMessageDialog(null, "Paket Dikonfirmasi!");
    }//GEN-LAST:event_jButtonKonfirmasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_AdminKonfirmasiPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_AdminKonfirmasiPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_AdminKonfirmasiPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_AdminKonfirmasiPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_AdminKonfirmasiPaket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonKonfirmasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKonfirmasi;
    private javax.swing.JTextField jTextIdBarang;
    private javax.swing.JTextField jTextIdKurir;
    private javax.swing.JTextField jTextIdPengiriman;
    private javax.swing.JTextField jTextStatus;
    // End of variables declaration//GEN-END:variables
}
