/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Login;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class V_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public V_Admin() {
        initComponents();
        try {
            welcome();
        } catch (SQLException ex) {
            Logger.getLogger(V_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void welcome() throws SQLException{
        Login l = new Login();
        jWelcome.setText("Selamat Datang, "+l.result.getString("nama")+"!");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jWelcome = new javax.swing.JLabel();
        jButtonCekBarang = new javax.swing.JButton();
        jButtonCekKurir = new javax.swing.JButton();
        jButtonCekUser = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 44)); // NOI18N
        jLabel10.setText("PACKETDOT");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(590, 40, 310, 54);

        jWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jWelcome.setText("Selamat Datang, nama_admin!");
        jPanel1.add(jWelcome);
        jWelcome.setBounds(100, 70, 370, 40);

        jButtonCekBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/barang-resize.png"))); // NOI18N
        jButtonCekBarang.setText("Cek Barang");
        jButtonCekBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCekBarangActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCekBarang);
        jButtonCekBarang.setBounds(110, 180, 160, 60);

        jButtonCekKurir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/kurir.png"))); // NOI18N
        jButtonCekKurir.setText("Cek Kurir");
        jButtonCekKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCekKurirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCekKurir);
        jButtonCekKurir.setBounds(300, 180, 160, 60);

        jButtonCekUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/edit.png"))); // NOI18N
        jButtonCekUser.setText("Cek User");
        jButtonCekUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCekUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCekUser);
        jButtonCekUser.setBounds(210, 260, 160, 60);

        jButtonLogOut.setText("Logout");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogOut);
        jButtonLogOut.setBounds(250, 380, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bg3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCekBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCekBarangActionPerformed
        // TODO add your handling code here:
        V_AdminCekBarang a = new V_AdminCekBarang();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonCekBarangActionPerformed

    private void jButtonCekKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCekKurirActionPerformed
        // TODO add your handling code here:
        V_AdminCekKurir k = new V_AdminCekKurir();
        k.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonCekKurirActionPerformed

    private void jButtonCekUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCekUserActionPerformed
        // TODO add your handling code here:
        V_AdminCekUser a = new V_AdminCekUser();
        a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonCekUserActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        V_Login l = new V_Login();
        l.setVisible(true);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCekBarang;
    private javax.swing.JButton jButtonCekKurir;
    private javax.swing.JButton jButtonCekUser;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jWelcome;
    // End of variables declaration//GEN-END:variables
}
