/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.User;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Model;

/**
 *
 * @author USER
 */
public class V_AdminCekUser extends javax.swing.JFrame {
    private Object id;
    /**
     * Creates new form AdminCekUser
     */
    public V_AdminCekUser() {
        initComponents();
        showTable();
        showSelected();
    }

    public void showTable(){
        DefaultTableModel tabelBar;
        String [] judulTabel = {"ID", "Nama", "Telepon", "Alamat", "Kota","Username"};
        tabelBar = new DefaultTableModel(judulTabel, 0);
        jTableUser.setModel(tabelBar);
        
        int row = jTableUser.getRowCount();
        for (int i = 0; i < row; i++) {
            tabelBar.removeRow(0);
        }
        
        try{
            User u = new User();
            ResultSet result = u.getAllUser();
            while(result.next()){
                String data[] = {result.getString("id"), result.getString("nama"), result.getString("telepon"), result.getString("alamat"), 
                    result.getString("kota"), result.getString("username")};
                tabelBar.addRow(data);
            }
        }catch(Exception e){
            System.err.println("error:");
        }
    }
    
    public void showSelected(){
        jTableUser.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
             if (e.getClickCount() == 1) {
              JTable target = (JTable)e.getSource();
              int row = target.getSelectedRow();
              int column = 0;
              id = target.getValueAt(row, column);
              try{
                  Model m = new Model();
                  String sql = "SELECT * FROM profile WHERE id = "+id;
                  ResultSet result = m.getData(sql);
                  while(result.next()){
                      jTextNama.setText(result.getString("nama"));
                      jTextTelepon.setText(result.getString("telepon"));
                      jTextAlamat.setText(result.getString("alamat"));
                      jTextKota.setText(result.getString("kota"));
                      jTextUsername.setText(result.getString("username"));
                  }
              } catch(Exception ex){
                  System.err.println("Error:");
              }
             }
            }
           });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextTelepon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextAlamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextKota = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextUsername = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUser);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 100, 790, 150);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("DETAIL USER");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(410, 270, 130, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 44)); // NOI18N
        jLabel10.setText("PACKETDOT");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 30, 280, 54);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("NAMA:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 320, 70, 22);
        jPanel1.add(jTextNama);
        jTextNama.setBounds(350, 310, 240, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("TELEPON:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 360, 100, 22);
        jPanel1.add(jTextTelepon);
        jTextTelepon.setBounds(350, 350, 240, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ALAMAT:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(220, 400, 90, 22);
        jPanel1.add(jTextAlamat);
        jTextAlamat.setBounds(350, 390, 240, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("KOTA:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 440, 70, 22);
        jPanel1.add(jTextKota);
        jTextKota.setBounds(350, 430, 240, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("USERNAME:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 480, 110, 22);
        jPanel1.add(jTextUsername);
        jTextUsername.setBounds(350, 470, 240, 30);

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete);
        jButtonDelete.setBounds(710, 490, 130, 40);

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/home.png"))); // NOI18N
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome);
        jButtonHome.setBounds(20, 20, 70, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bg9.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        User u = new User((String) id);
        int set = JOptionPane.showConfirmDialog(null, "Apa Anda Yakin akan Menghapus Data?");
        if (set == 0){
            u.deleteuser();
            showTable();
            jTextNama.setText("");
            jTextTelepon.setText("");
            jTextAlamat.setText("");
            jTextKota.setText("");
            jTextUsername.setText("");
            JOptionPane.showMessageDialog(null, "User Berhasil Dihapus!");
        }
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        V_Admin a = new V_Admin();
        a.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_AdminCekUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_AdminCekUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_AdminCekUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_AdminCekUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_AdminCekUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUser;
    private javax.swing.JTextField jTextAlamat;
    private javax.swing.JTextField jTextKota;
    private javax.swing.JTextField jTextNama;
    private javax.swing.JTextField jTextTelepon;
    private javax.swing.JTextField jTextUsername;
    // End of variables declaration//GEN-END:variables
}
