/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Barang;
import controller.Kurir;
import controller.Login;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Model;

/**
 *
 * @author USER
 */
public class V_KurirAmbilBarang extends javax.swing.JFrame {
    private Object resi;
    private String stat;
    /**
     * Creates new form KurirAmbilBarang
     */
    public V_KurirAmbilBarang() {
        initComponents();
        
        jTextNamaPengirim.setEditable(false);
        jTextAlamatPengirim.setEditable(false);
        jTextKotaPengirim.setEditable(false);
        jTextTeleponPengirim.setEditable(false);
        jTextNamaPenerima.setEditable(false);
        jTextAlamatPenerima.setEditable(false);
        jTextKotaPenerima.setEditable(false);
        jTextTeleponPenerima.setEditable(false);
        jTextNamaBarang.setEditable(false);
        jTextBeratBarang.setEditable(false);
        jTextJenis.setEditable(false);
        jTextStatus.setEditable(false);
        
        showTable();
        showSelected();
    }

    public void showTable(){
        DefaultTableModel tabelBar;
        String [] judulTabel = {"Resi", "Barang", "Penerima", "Alamat", "Telepon", "Status"};
        tabelBar = new DefaultTableModel(judulTabel, 0);
        jTableBarang.setModel(tabelBar);
        
        int row = jTableBarang.getRowCount();
        for (int i = 0; i < row; i++) {
            tabelBar.removeRow(0);
        }
        
        try{
            Kurir k = new Kurir();
            ResultSet result = k.getPaket();
            while(result.next()){
                String data[] = {result.getString("id"), result.getString("nama_barang"), result.getString("nama_penerima"), result.getString("alamat_penerima"), 
                    result.getString("telepon_penerima"),result.getString("status")};
                tabelBar.addRow(data);
            }
        }catch(Exception e){
            System.err.println("error: showTable()");
        }
    }
    
    public void showSelected(){
        jTableBarang.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
             if (e.getClickCount() == 1) {
              JTable target = (JTable)e.getSource();
              int row = target.getSelectedRow();
              int column = 0;
              resi = target.getValueAt(row, column);
              try{
                  Model m = new Model();
                  String sql = "SELECT * FROM barang WHERE id = '"+resi+"'";
                  ResultSet result = m.getData(sql);
                  while(result.next()){
                      jTextNamaPengirim.setText(result.getString("nama_pengirim"));
                      jTextAlamatPengirim.setText(result.getString("alamat_pengirim"));
                      jTextKotaPengirim.setText(result.getString("kota_pengirim"));
                      jTextTeleponPengirim.setText(result.getString("telepon_pengirim"));
                      jTextNamaPenerima.setText(result.getString("nama_penerima"));
                      jTextAlamatPenerima.setText(result.getString("alamat_penerima"));
                      jTextKotaPenerima.setText(result.getString("kota_penerima"));
                      jTextTeleponPenerima.setText(result.getString("telepon_penerima"));
                      jTextNamaBarang.setText(result.getString("nama_barang"));
                      jTextBeratBarang.setText(result.getString("berat_barang"));
                      jTextJenis.setText(result.getString("jenis_pengiriman"));
                      jTextStatus.setText(result.getString("status"));
                      stat = result.getString("status");
                  }
              } catch(Exception ex){
                  System.err.println("Error: showSelected()");
              }
             }
            }
           });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBarang = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextNamaPengirim = new javax.swing.JTextField();
        jTextAlamatPengirim = new javax.swing.JTextField();
        jTextKotaPengirim = new javax.swing.JTextField();
        jTextTeleponPengirim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextNamaPenerima = new javax.swing.JTextField();
        jTextKotaPenerima = new javax.swing.JTextField();
        jTextAlamatPenerima = new javax.swing.JTextField();
        jTextTeleponPenerima = new javax.swing.JTextField();
        jTextNamaBarang = new javax.swing.JTextField();
        jTextBeratBarang = new javax.swing.JTextField();
        jTextJenis = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextStatus = new javax.swing.JTextField();
        jButtonAmbilPaket = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableBarang);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 80, 820, 120);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 44)); // NOI18N
        jLabel10.setText("PACKETDOT");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 10, 280, 54);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("DETAIL PENGIRIMAN");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(410, 210, 200, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Data Pengirim");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 260, 129, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama Pengirim:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 300, 125, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Alamat Pengirim:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 330, 134, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Kota Pengirim:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 360, 116, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Telepon:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(150, 390, 69, 20);
        jPanel1.add(jTextNamaPengirim);
        jTextNamaPengirim.setBounds(300, 300, 183, 30);
        jPanel1.add(jTextAlamatPengirim);
        jTextAlamatPengirim.setBounds(300, 330, 183, 30);
        jPanel1.add(jTextKotaPengirim);
        jTextKotaPengirim.setBounds(300, 360, 183, 30);
        jPanel1.add(jTextTeleponPengirim);
        jTextTeleponPengirim.setBounds(300, 390, 183, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Data Penerima");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(510, 260, 135, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nama Penerima:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(510, 300, 129, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Alamat Penerima:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 330, 138, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Kota Penerima:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(510, 360, 130, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Telepon:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(510, 390, 69, 20);
        jPanel1.add(jTextNamaPenerima);
        jTextNamaPenerima.setBounds(660, 300, 183, 30);
        jPanel1.add(jTextKotaPenerima);
        jTextKotaPenerima.setBounds(660, 360, 183, 30);
        jPanel1.add(jTextAlamatPenerima);
        jTextAlamatPenerima.setBounds(660, 330, 183, 30);
        jPanel1.add(jTextTeleponPenerima);
        jTextTeleponPenerima.setBounds(660, 390, 183, 30);
        jPanel1.add(jTextNamaBarang);
        jTextNamaBarang.setBounds(300, 490, 183, 30);
        jPanel1.add(jTextBeratBarang);
        jTextBeratBarang.setBounds(300, 520, 183, 30);
        jPanel1.add(jTextJenis);
        jTextJenis.setBounds(300, 550, 183, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Data Barang");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(150, 460, 113, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Nama Barang:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(150, 490, 112, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Berat Barang:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(150, 520, 108, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("STATUS");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(540, 470, 70, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Jenis Pengiriman:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(150, 550, 138, 20);
        jPanel1.add(jTextStatus);
        jTextStatus.setBounds(660, 460, 180, 30);

        jButtonAmbilPaket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAmbilPaket.setText("Ambil Paket");
        jButtonAmbilPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmbilPaketActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAmbilPaket);
        jButtonAmbilPaket.setBounds(650, 520, 190, 60);

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/home.png"))); // NOI18N
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome);
        jButtonHome.setBounds(10, 10, 70, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bg7.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAmbilPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilPaketActionPerformed
        try {
            // TODO add your handling code here:
            Login l = new Login();
            Model m = new Model();
            Kurir k = new Kurir(Integer.parseInt(l.getId_login()),this.resi, this.stat);
            if (k.setAmbilBarang()){
                JOptionPane.showMessageDialog(null, "Paket Berhasil Diproses, Silahkan Tunggu Konfirmasi Admin!");
            } else{
                JOptionPane.showMessageDialog(null, "Paket Sudah Diproses, Silahkan Pilih Paket Lain!");
            }
            showTable();
        } catch (SQLException ex) {
            System.err.println("Error: "+ex);
        }
    }//GEN-LAST:event_jButtonAmbilPaketActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        V_Kurir k = new V_Kurir();
        k.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_KurirAmbilBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_KurirAmbilBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_KurirAmbilBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_KurirAmbilBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_KurirAmbilBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAmbilPaket;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBarang;
    private javax.swing.JTextField jTextAlamatPenerima;
    private javax.swing.JTextField jTextAlamatPengirim;
    private javax.swing.JTextField jTextBeratBarang;
    private javax.swing.JTextField jTextJenis;
    private javax.swing.JTextField jTextKotaPenerima;
    private javax.swing.JTextField jTextKotaPengirim;
    private javax.swing.JTextField jTextNamaBarang;
    private javax.swing.JTextField jTextNamaPenerima;
    private javax.swing.JTextField jTextNamaPengirim;
    private javax.swing.JTextField jTextStatus;
    private javax.swing.JTextField jTextTeleponPenerima;
    private javax.swing.JTextField jTextTeleponPengirim;
    // End of variables declaration//GEN-END:variables
}
