/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Barang;
import controller.Login;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class V_UserKirimBarang extends javax.swing.JFrame {
    
    /**
     * Creates new form UserKirimBarang
     */
    public V_UserKirimBarang() {
        initComponents();
        setTextField();
    }
    
    public void setTextField(){
        try {
            Login l = new Login();
            ResultSet result = l.getUserData();
            if(result.next()){
                jTextNamaPengirim.setText(result.getString("nama"));
                jTextAlamatPengirim.setText(result.getString("alamat"));
                jTextKotaPengirim.setText(result.getString("kota"));
                jTextTeleponPengirim.setText(result.getString("telepon"));
            }
        } catch (SQLException ex) {
            System.err.println("Error : setTextField()");
        }
    }
    
    public int biaya(){
        int biaya;
        String kotaKirim = jTextKotaPengirim.getText();
        String kotaTerima = jTextKotaPenerima.getText();
        int beratBarang = Integer.parseInt(jTextBeratBarang.getText());
        String jenisPengiriman = (String) jComboBoxJenis.getSelectedItem();
        biaya = 10000;
        int biayaPerKilo = 2000;
        
        if ("Express".equals(jenisPengiriman)){
            biaya += 10000;
        }
        
        if (!kotaTerima.equals(kotaKirim)){
            biaya += 5000;
        }
        biaya += biayaPerKilo*beratBarang;
        
        return biaya;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        jTextNamaPenerima = new javax.swing.JTextField();
        jTextNamaPengirim = new javax.swing.JTextField();
        jTextAlamatPengirim = new javax.swing.JTextField();
        jTextKotaPengirim = new javax.swing.JTextField();
        jTextTeleponPengirim = new javax.swing.JTextField();
        jTextTeleponPenerima = new javax.swing.JTextField();
        jTextKotaPenerima = new javax.swing.JTextField();
        jTextAlamatPenerima = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextNamaBarang = new javax.swing.JTextField();
        jTextBeratBarang = new javax.swing.JTextField();
        jButtonPickUp = new javax.swing.JButton();
        jComboBoxJenis = new javax.swing.JComboBox<>();
        jButtonBiayaPengiriman = new javax.swing.JButton();
        jLabelBiaya = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel10.setText("PACKETDOT");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(400, 20, 200, 37);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("KIRIM BARANG");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 60, 190, 29);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Telepon:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 400, 69, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Data Pengirim");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 100, 129, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nama Pengirim:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 140, 125, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Alamat Pengirim:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 170, 134, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Kota Pengirim:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 200, 116, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Data Penerima");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 280, 135, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nama Penerima:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 310, 129, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Alamat Penerima:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 340, 138, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Kota Penerima:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 370, 130, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Telepon:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 230, 69, 22);

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/home.png"))); // NOI18N
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome);
        jButtonHome.setBounds(910, 20, 67, 70);
        jPanel1.add(jTextNamaPenerima);
        jTextNamaPenerima.setBounds(170, 310, 183, 30);
        jPanel1.add(jTextNamaPengirim);
        jTextNamaPengirim.setBounds(170, 140, 183, 30);
        jPanel1.add(jTextAlamatPengirim);
        jTextAlamatPengirim.setBounds(170, 170, 183, 30);
        jPanel1.add(jTextKotaPengirim);
        jTextKotaPengirim.setBounds(170, 200, 183, 30);
        jPanel1.add(jTextTeleponPengirim);
        jTextTeleponPengirim.setBounds(170, 230, 183, 30);
        jPanel1.add(jTextTeleponPenerima);
        jTextTeleponPenerima.setBounds(170, 400, 183, 30);
        jPanel1.add(jTextKotaPenerima);
        jTextKotaPenerima.setBounds(170, 370, 183, 30);
        jPanel1.add(jTextAlamatPenerima);
        jTextAlamatPenerima.setBounds(170, 340, 183, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Data Barang");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 440, 113, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Nama Barang:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 470, 112, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Berat Barang:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 500, 108, 22);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Jenis Pengiriman:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 530, 138, 22);
        jPanel1.add(jTextNamaBarang);
        jTextNamaBarang.setBounds(170, 470, 183, 30);
        jPanel1.add(jTextBeratBarang);
        jTextBeratBarang.setBounds(170, 500, 183, 30);

        jButtonPickUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonPickUp.setText("Request Pick Up");
        jButtonPickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPickUpActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPickUp);
        jButtonPickUp.setBounds(590, 510, 230, 70);

        jComboBoxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Express" }));
        jPanel1.add(jComboBoxJenis);
        jComboBoxJenis.setBounds(170, 530, 180, 30);

        jButtonBiayaPengiriman.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBiayaPengiriman.setText("Cek Biaya Pengiriman");
        jButtonBiayaPengiriman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBiayaPengirimanActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBiayaPengiriman);
        jButtonBiayaPengiriman.setBounds(400, 120, 230, 30);

        jLabelBiaya.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelBiaya.setText("Biaya Pengiriman: -");
        jPanel1.add(jLabelBiaya);
        jLabelBiaya.setBounds(400, 160, 280, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bg4.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        V_User u = new V_User();
        u.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonPickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPickUpActionPerformed
        // TODO add your handling code here:
        String namaKirim = jTextNamaPengirim.getText();
        String alamatKirim = jTextAlamatPengirim.getText();
        String kotaKirim = jTextKotaPengirim.getText();
        String teleponKirim = jTextTeleponPengirim.getText();
        String namaTerima = jTextNamaPenerima.getText();
        String alamatTerima = jTextAlamatPenerima.getText();
        String kotaTerima = jTextKotaPenerima.getText();
        String teleponTerima = jTextTeleponPenerima.getText();
        String namaBarang = jTextNamaBarang.getText();
        String beratBarang = jTextBeratBarang.getText();
        String jenisPengiriman = (String) jComboBoxJenis.getSelectedItem();
        
        try{
            if(namaKirim.equals("") || alamatKirim.equals("") || kotaKirim.equals("") || teleponKirim.equals("") || namaTerima.equals("") || alamatTerima.equals("") || kotaTerima.equals("") ||
                    teleponTerima.equals("") || namaBarang.equals("") || beratBarang.equals("")){
                JOptionPane.showMessageDialog(null, "Isi Semua Data!");
            } else{
                Barang b = new Barang(namaKirim, alamatKirim, kotaKirim, teleponKirim, namaTerima, alamatTerima, kotaTerima, teleponTerima, namaBarang, beratBarang, jenisPengiriman);
                String in = JOptionPane.showInputDialog(null, "Isi Pembayaran Sejumlah: Rp "+biaya());
                if (Float.parseFloat(in)==biaya()){
                    b.setBarang();
                    JOptionPane.showMessageDialog(null, "Barang Berhasil Diproses!");
                    V_UserCekBarang u =  new V_UserCekBarang();
                    u.setVisible(true);
                    setVisible(false);
                } else{
                    JOptionPane.showMessageDialog(null, "Pembayaran Tidak Sesuai!");
                }
            }
        } catch (Exception e){
            System.err.println("Error:"+e);
        }
    }//GEN-LAST:event_jButtonPickUpActionPerformed

    private void jButtonBiayaPengirimanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBiayaPengirimanActionPerformed
        // TODO add your handling code here:
        jLabelBiaya.setText("Biaya Pengiriman: Rp "+biaya());
    }//GEN-LAST:event_jButtonBiayaPengirimanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_UserKirimBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_UserKirimBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_UserKirimBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_UserKirimBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_UserKirimBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBiayaPengiriman;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonPickUp;
    private javax.swing.JComboBox<String> jComboBoxJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBiaya;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextAlamatPenerima;
    private javax.swing.JTextField jTextAlamatPengirim;
    private javax.swing.JTextField jTextBeratBarang;
    private javax.swing.JTextField jTextKotaPenerima;
    private javax.swing.JTextField jTextKotaPengirim;
    private javax.swing.JTextField jTextNamaBarang;
    private javax.swing.JTextField jTextNamaPenerima;
    private javax.swing.JTextField jTextNamaPengirim;
    private javax.swing.JTextField jTextTeleponPenerima;
    private javax.swing.JTextField jTextTeleponPengirim;
    // End of variables declaration//GEN-END:variables
}
