/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Login;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Model;

/**
 *
 * @author USER
 */
public class V_UserEditProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserEditProfile
     */
    public V_UserEditProfile() {
        initComponents();
        initTextField();
    }

    public void initTextField(){
        try {
            Login l = new Login();
            ResultSet result = l.getUserData();
            while(result.next()){
                jTextNama.setText(result.getString("nama"));
                jTextTelepon.setText(result.getString("telepon"));
                jTextAlamat.setText(result.getString("alamat"));
                jTextKota.setText(result.getString("kota"));
                jTextUsername.setText(result.getString("username"));
                jTextPassword.setText(result.getString("password"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(V_UserEditProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jTextNama = new javax.swing.JTextField();
        jTextPassword = new javax.swing.JTextField();
        jTextUsername = new javax.swing.JTextField();
        jTextTelepon = new javax.swing.JTextField();
        jTextAlamat = new javax.swing.JTextField();
        jTextKota = new javax.swing.JTextField();
        jButtonHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("USERNAME:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 290, 110, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("PASSWORD:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 330, 130, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("NAMA:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 130, 70, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("TELEPON:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 170, 100, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel10.setText("PACKETDOT");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(170, 40, 240, 44);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("EDIT PROFILE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 80, 140, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ALAMAT:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 210, 90, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("KOTA:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 250, 70, 22);

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSubmit);
        jButtonSubmit.setBounds(220, 380, 146, 41);
        jPanel1.add(jTextNama);
        jTextNama.setBounds(180, 120, 240, 30);
        jPanel1.add(jTextPassword);
        jTextPassword.setBounds(180, 320, 240, 30);
        jPanel1.add(jTextUsername);
        jTextUsername.setBounds(180, 280, 240, 30);
        jPanel1.add(jTextTelepon);
        jTextTelepon.setBounds(180, 160, 240, 30);
        jPanel1.add(jTextAlamat);
        jTextAlamat.setBounds(180, 200, 240, 30);
        jPanel1.add(jTextKota);
        jTextKota.setBounds(180, 240, 240, 30);

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/home.png"))); // NOI18N
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome);
        jButtonHome.setBounds(20, 490, 60, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bg4.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 510, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        try {
            Login l = new Login();
            Model m = new Model();
            String sql = "UPDATE profile SET nama = '"+jTextNama.getText()+"', telepon = '"+jTextTelepon.getText()+"', alamat = '"+jTextAlamat.getText()+"', kota = '"+jTextKota.getText()
                    +"', username = '"+jTextUsername.getText()+"', password = '"+jTextPassword.getText()+"' WHERE id = '"+l.getId_login()+"'";
            m.updateData(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate!");
        } catch (SQLException ex) {
            Logger.getLogger(V_UserEditProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        V_User u = new V_User();
        u.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_UserEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_UserEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_UserEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_UserEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_UserEditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextAlamat;
    private javax.swing.JTextField jTextKota;
    private javax.swing.JTextField jTextNama;
    private javax.swing.JTextField jTextPassword;
    private javax.swing.JTextField jTextTelepon;
    private javax.swing.JTextField jTextUsername;
    // End of variables declaration//GEN-END:variables
}
